---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name: Remove automatic updates
      apt:
        name: unattended-upgrades
        state: absent

    - name: Base dependencies
      apt:
        pkg:
          - sshpass
          - nmap
          - ncat
        state: present
        update_cache: yes
