---
- hosts: "{{ host }}"
  remote_user: root

  # 
  tasks:
    - name: Remove automatic updates
      apt:
        name: unattended-upgrades
        state: absent

    - name: Base dependencies
      apt:
        pkg:
          - kali-linux-headless
          - net-tools
          - curl
          - wget
          - sshpass
          - nmap
          - ncat
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install stormssh
      ansible.builtin.pip:
        name: stormssh
        extra_args: --break-system-packages
