name: openstack
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=21.2.4
  - python=3.10.4
  - setuptools=58.0.4
  - pycryptodome
  - pip:
    - ansible
    - ansible-runner==2.2.1
    - openstacksdk==0.61.0
    - python-openstackclient==5.8.0
    - pyyaml==6.0
    - requests==2.27.1
    - rich==12.5.1
    - flask
    - colorama
    - prompt-toolkit
    - rich
    - console
