---
- hosts: "{{ host }}"
  remote_user: root

- name: Allow traffic on port 21
  ansible.builtin.import_playbook: ../common/allowTraffic.yml
  vars:
    port_no: "21"
    proto: tcp

- name: Execute vsftpd
  hosts: "{{ host }}"
  tasks:
  - name: Execute vsftpd
    shell: "vsftpd >/dev/null 2>&1 &"