---
- hosts: "{{ host }}"
  remote_user: root

- name: Allow traffic on port 21
  ansible.builtin.import_playbook: ../common/allowTraffic.yml
  vars:
    port_no: "21"
    proto: tcp

- name: Add i386 architecture
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: /usr/bin/dpkg --add-architecture i386 

- name: apt-get update
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: /usr/bin/apt-get update

- name: Install build-essential
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: build-essential

- name: Install libssl-dev
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: libssl-dev

- name: Install libpam0g-dev
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: libpam0g-dev

- name: Install libssl-dev:i386
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: libssl-dev:i386

- name: Install libpam0g-dev:i386
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: libpam0g-dev:i386

- name: Install gcc-multilib
  ansible.builtin.import_playbook: ../common/installPackage.yml
  vars:
    package: gcc-multilib

- name: Download vsftp234 makefile
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: wget https://raw.githubusercontent.com/cliffe/SecGen/master/modules/vulnerabilities/unix/ftp/vsftpd_234_backdoor/files/Makefile -O ~/Makefile

- name: Download vsftp234 installer archive
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: wget https://raw.githubusercontent.com/cliffe/SecGen/master/modules/vulnerabilities/unix/ftp/vsftpd_234_backdoor/files/vsftpd-2.3.4.tar.gz -O ~/vsftpd-2.3.4.tar.gz

- name: Create /usr/share/empty directory if it does not exist
  ansible.builtin.import_playbook: ../common/createDirectory.yml
  vars:
    cpath: '/usr/share/empty'
    dmode: '0755'

- name: Create /var/ftp directory if it does not exist
  ansible.builtin.import_playbook: ../common/createDirectory.yml
  vars:
    cpath: '/var/ftp'
    dmode: '0755'

- name: Create /usr/local/man/man5 directory if it does not exist
  ansible.builtin.import_playbook: ../common/createDirectory.yml
  vars:
    cpath: '/usr/local/man/man5'
    dmode: '0755'

- name: Create /usr/local/man/man8 directory if it does not exist
  ansible.builtin.import_playbook: ../common/createDirectory.yml
  vars:
    cpath: '/usr/local/man/man8'
    dmode: '0755'

- name: Extract vsftpd installer archive
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: tar -xzf ~/vsftpd-2.3.4.tar.gz -C /usr/local/src/

- name: Copy MakeFile
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: cp ~/Makefile /usr/local/src/vsftpd-2.3.4/

- name: Make
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: make -C /usr/local/src/vsftpd-2.3.4/

- name: Make install
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: make install -C /usr/local/src/vsftpd-2.3.4/

- name: Download vsftpd init.d file
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: wget https://raw.githubusercontent.com/cliffe/SecGen/master/modules/vulnerabilities/unix/ftp/vsftpd_234_backdoor/files/vsftpd_init.d -O /etc/init.d/vsftpd

- name: Download vsftpd config file
  ansible.builtin.import_playbook: ../common/runCommand.yml
  vars:
    command: wget https://raw.githubusercontent.com/cliffe/SecGen/master/modules/vulnerabilities/unix/ftp/vsftpd_234_backdoor/files/vsftpd.conf -O /etc/vsftpd.conf

- name: Run vsftpd
  hosts: "{{ host }}"
  tasks:
  - name: Execute vsftpd
    shell: "vsftpd >/dev/null 2>&1 &"
