---
- hosts: "{{ host }}"
  become: true
  become_user: '{{ user }}'

  tasks:
    - copy:
        src: "install_attacker.sh"
        dest: "~/install_attacker.sh"

    - command: "chmod +x ~/install_attacker.sh"

    - name: Run installer
      become: true
      become_user: '{{ user }}'
      shell: 
        cmd: "nohup ~/install_attacker.sh {{ caldera_ip }} >/dev/null 2>&1 &"
        chdir: "~/"
