FROM ubuntu:latest

SHELL ["/bin/bash", "-c"]

# Get miniconda
RUN apt-get update && \
    apt-get -y install wget && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH="/opt/conda/bin:$PATH"

# Activate conda
RUN source /opt/conda/bin/activate
RUN conda init 
RUN conda create --name caldera python=3.10 -y
RUN /opt/conda/bin/activate caldera

# Install dependencies
RUN apt-get -y install git golang-go

RUN git clone https://github.com/bsinger98/caldera.git --recursive

WORKDIR /caldera

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 8888
# Default HTTPS port for web interface and agent beacons over HTTPS (requires SSL plugin to be enabled)
EXPOSE 8443
# TCP and UDP contact ports
EXPOSE 7010
EXPOSE 7011/udp
# Websocket contact port
EXPOSE 7012
# Default port to listen for DNS requests for DNS tunneling C2 channel
EXPOSE 8853
# Default port to listen for SSH tunneling requests
EXPOSE 8022
# Default FTP port for FTP C2 channel
EXPOSE 2222

CMD ["python3", "server.py", "--insecure", "--fresh"]