FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3 python3-venv 

RUN apt-get install -y git golang-go

RUN git clone https://github.com/bsinger98/caldera.git /home/caldera --recursive

WORKDIR /home/caldera

RUN pip3 install -r requirements.txt --no-cache-dir

CMD ["tail", "-f", "/dev/null"]