FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip python-is-python3 python3-venv 

RUN apt-get install -y git golang-go

RUN git clone https://github.com/bsinger98/caldera.git /home/caldera --recursive

WORKDIR /home/caldera

RUN pip3 install -r requirements.txt --no-cache-dir

EXPOSE 8888
# Default HTTPS port for web interface and agent beacons over HTTPS (requires SSL plugin to be enabled)
EXPOSE 8443
# TCP and UDP contact ports
EXPOSE 7010
EXPOSE 7011/udp
# Websocket contact port
EXPOSE 7012
# Default port to listen for DNS requests for DNS tunneling C2 channel
EXPOSE 8853
# Default port to listen for SSH tunneling requests
EXPOSE 8022
# Default FTP port for FTP C2 channel
EXPOSE 2222

CMD ["tail", "-f", "/dev/null"]