---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
    - name: Update the System Packages
      apt:
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: default-jdk
        update_cache: yes
        state: present

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat
      unarchive:
        src: apache-tomcat-9.0.83.tar.gz
        dest: /opt/tomcat
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy demo apache strut webapp
      copy:
        owner: tomcat
        group: tomcat
        src: apps/struts2-showcase.war
        dest: /opt/tomcat/webapps/
        mode: 0755

    - name: Copy Tomcat service from local to remote
      copy:
        src: tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: Start and Enable Tomcat on sever
      systemd:
        name: tomcat
        state: started
        enabled: true
        daemon_reload: true
