---
- hosts: nodes
  remote_user: ubuntu
  vars:
          ansible_ssh_private_key_file: "{{ ssh_key_path }}"

  tasks:
          - copy:
                  src: "{{ local_path }}"
                  dest: "{{ remote_path }}"

          - name: Run installer
            command: "{{ remote_path}}"
            register: op
          - debug: 
                var: op.stdout
