---
- hosts: "{{ host }}"
  tasks:
    - name: delete ssh copnfig
      become: true
      become_user: "{{ host_user }}"
      file:
        path: "~/.ssh/config"
        state: absent

    - name: Touch ssh copnfig
      become: true
      become_user: "{{ host_user }}"
      file:
        path: "~/.ssh/config"
        state: touch
        mode: "0600"
    
