---
- hosts: "{{ host }}"
  remote_user: root

  tasks:
  # Add 'ALL ALL = (root) sudoedit /etc/hosts' to /etc/sudoers
  # - name: Add specific rule for sudoedit in /etc/sudoers
  #   ansible.builtin.lineinfile:
  #     path: /etc/sudoers
  #     line: 'ALL ALL = (root) NOPASSWD: sudoedit /etc/hosts'
  #     state: present
  #     mode: '0440'
  #     owner: root
  #     group: root
  
  # Add 'ALL ALL = (root) sudoedit /etc/hosts' to /etc/sudoers.d/sudoedit
  - name: Add rule to allow editing /etc/hosts as root using sudoedit
    copy:
      dest: /etc/sudoers.d/sudoedit_hosts
      content: |
        ALL ALL = (root) sudoedit /etc/hosts
      owner: root
      group: root
      mode: '0440'

  - name: Ensure sudo lecture is disabled
    lineinfile:
      path: /etc/sudoers.d/disable_lecture
      state: present
      line: 'Defaults lecture=never'
      create: yes
      owner: root
      group: root
      mode: '0440'

  - name: Create a sudoers file to disable password prompts for all users
    copy:
      dest: /etc/sudoers.d/disable_sudo_password
      content: |
        ALL ALL=(ALL) NOPASSWD:ALL
      owner: root
      group: root
      mode: '0440'
    
  # - name: Ensure sudo lecture is disabled
  #   ansible.builtin.lineinfile:
  #     path: /etc/sudoers
  #     line: 'Defaults lecture=never'
  #     state: present
  #     mode: '0440'
  #     owner: root
  #     group: root



  - name: Copy sudo.deb
    copy:
      src: sudo_1.8.26-2_amd64.deb
      dest: /tmp/sudo_1.8.26-2_amd64.deb

  - name: Install sudo
    apt:
      deb: /tmp/sudo_1.8.26-2_amd64.deb
      state: present
      force: yes
      
